apiVersion: v2
name: next_chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus-stack
    version: 61.0.0   # глянуть более актуальную версию если понадобится
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled # не забыть указать в values
    
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami 
    alias: postgresqlbitnami # переменные просто для раздела postgresql в values уже заняты подом для тестов, потому тут укажу на раздел postgresqlbitnami 
    condition: postgresqlbitnami.enabled
